# Version of the specs, only for internal usage if this format should ever change drastically
_specver: 2

# modpack related settings, changes the supposed to change the visual appearance of the launcher
modpack:
  name: Ragnamod V
  description: Ragnamod V By MLDEG & Alkasym

# settings regarding the installation of the modpack
install:
  # version of minecraft, needs the exact version
  mcVersion: 1.12.2
  loaderVersion: ~
  installerUrl: "http://files.minecraftforge.net/maven/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/forge-{{@mcversion@}}-{{@loaderversion@}}-installer.jar"
  installerArguments:
    - "--installServer"
  modpackUrl: https://media.forgecdn.net/files/2878/138/Ragnamod+V-5.8.0.zip
  modpackFormat: curse

  # Settings which are specific to the format used, might not be needed in some casese
  formatSpecific:
    # optional paramenter used for curse to specify a whole project to ignore (mostly if it is client side only)
    ignoreProject:
      - 263420
      - 317780
      - 232131
      - 231275
      - 367706
      - 261725
      - 243863
      - 305373
      - 325492
      - 296468
      - 308240
      - 362791
      - 291788
      - 326950
      - 237701
      - 391382
      - 358191
      - 271740
      - 428199
      - 431430
      - 270441
      - 251407
      - 250398
      - 233071
      - 226406
      - 282743
      - 265917
      - 267939
      - 303122
      - 238747
      - 243478
      - 60089
      - 226447
      - 285492
      - 242106 # Better Questing - Quest Book
      - 417179 # Caged Mobs
      - 428877 # BetterEnd (Forge)
      - 400012 # Ex Nihilo: Sequentia
      - 245174 # Ender Storage 1.8.+
      - 74254 # Moo Fluids
      - 222880 # Thermal Foundation

  baseInstallPath: server/
  ignoreFiles:
    - mods/Overrides.txt
    - mods/optifine*.jar
    - mods/optiforge*.jar
    - resources/**
    - openloader/resources/**

  additionalFiles:
  localFiles:
    - from: server-icon.png
      to: server/server-icon.png
    - from: server.properties
      to: server/server.properties
    - from: mods/ThermalFoundation-1.12.2-2.6.3.27-universal.jar
      to: server/mods/ThermalFoundation-1.12.2-2.6.3.27-universal.jar
    - from: mods/MooFluids-1.12.2-1.8.12.02a.jar
      to: server/mods/MooFluids-1.12.2-1.8.12.02a.jar
    - from: mods/questbook-3.1.1-1.12.jar
      to: server/mods/questbook-3.1.1-1.12.jar
    - from: mods/ThermalFoundation-1.12.2-2.6.3.27-universal.jar
      to: server/mods/ThermalFoundation-1.12.2-2.6.3.27-universal.jar
  checkFolder: true
  installLoader: true
  spongeBootstrapper: https://github.com/simon816/SpongeBootstrap/releases/download/v0.7.1/SpongeBootstrap-0.7.1.jar
  connectTimeout: 30
  readTimeout: 30

  # In order to obtain the download urls for mods enclosed in a curseforge format, you must provide an
  # API key. Please visit https://github.com/Ocraftyone/ServerStarter-CFCorePatch for more details
  # on how to obtain a key. This can be omitted if you are using the zip modpackFormat.
  curseForgeAPIKey: XXX

# settings regarding the launching of the pack
launch:
  spongefix: false
  ramDisk: false
  checkOffline: true
  checkUrls:
    - https://github.com/
    - https://www.curseforge.com/
  maxRam: 12G
  minRam: 8G
  autoRestart: true
  crashLimit: 10
  crashTimer: 60min
  preJavaArgs: ~
  startFile: "forge-{{@mcversion@}}-{{@loaderversion@}}-universal.jar"
  # For <1.16 it should be
  #  - "-jar"
  #  - "{{@startFile@}}"
  #  - "nogui"
  # For >=1.17 it should be
  # - "@libraries/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/{{@os@}}_args.txt"
  # - "nogui"
  startCommand:
    - "-jar"
    - "{{@startFile@}}"
    - "nogui"
  forcedJavaPath: ~
  javaArgs:
    - "-Dfml.readTimeout=600"
    - "-Dfml.loginTimeout=600"
    - "-Dfml.queryResult=confirm"
    - "-XX:+UseG1GC"
    - "-XX:+ParallelRefProcEnabled"
    - "-XX:MaxGCPauseMillis=200"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+DisableExplicitGC"
    - "-XX:+AlwaysPreTouch"
    - "-XX:G1NewSizePercent=30"
    - "-XX:G1MaxNewSizePercent=40"
    - "-XX:G1HeapRegionSize=8M"
    - "-XX:G1ReservePercent=20"
    - "-XX:G1HeapWastePercent=5"
    - "-XX:G1MixedGCCountTarget=4"
    - "-XX:InitiatingHeapOccupancyPercent=15"
    - "-XX:G1MixedGCLiveThresholdPercent=90"
    - "-XX:G1RSetUpdatingPauseTimePercent=5"
    - "-XX:SurvivorRatio=32"
    - "-XX:+PerfDisableSharedMem"
    - "-XX:MaxTenuringThreshold=1"
